const EMOJI_VIRTUAL = '🖲️';
const EMOJI_ORDER = '📦';
const EMOJI_WARNING = '⚠️';
const EMOJI_CHECK = '✅';
const EMOJI_CROSS = '❌';
const EMOJI_CLOSE = '✖️';
const EMOJI_MOVE_DOWN = '⏬';
const EMOJI_MOVE_UP = '⏫';
const EMOJI_BALANCE = '💰';
const EMOJI_SETTINGS = '⚙️';
const EMOJI_TRIGGERS = '🔔';
const EMOJI_LIST = '📋';
const EMOJI_DIAGNOSTIC = '🩺';
const EMOJI_WEBSOCKET = '📡';
const EMOJI_CHART = '📊';
const EMOJI_WRENCH = '🔧';
const EMOJI_PENDING = '⏳';
const EMOJI_LONG = '🚀';
const EMOJI_SHORT = '🔻';
const EMOJI_NEAR_MISS = '⚠️';
const EMOJI_PAUSE = '⏸';
const EMOJI_PLAY = '▶️';
const EMOJI_INFO = 'ℹ️';
const EMOJI_STALE = '⚠️';
const EMOJI_LONG_DOT = '🟢';
const EMOJI_SHORT_DOT = '🔴';
const EMOJI_RESTART = '🔄';
const EMOJI_UPTIME = '⏱';
const EMOJI_CIRCUIT_BREAKER = '🚨';
const EMOJI_TRADING_PAUSED = '🚨';
const EMOJI_SOS = '🆘';
const EMOJI_RULER = '📐';
const EMOJI_MULTI = '🔢';
const EMOJI_SNAIL = '🐌';
const EMOJI_MA_APPROACH = '🤏';
const EMOJI_MA_CROSS = '⚒️';
const EMOJI_SCISSORS = '✂️';
const EMOJI_VOLCANO = '🌋';
const EMOJI_TARGET = '🎯';
const EMOJI_SIGMA = 'Σ';
const EMOJI_PROFIT = '💰';
const EMOJI_SEARCH = '🩻';
const EMOJI_ROBOT = '🤖';
const EMOJI_DOOR = '🚪';
const EMOJI_SCALE = '⚖️';
const EMOJI_NO_MA_TOUCH = '🪂';
const EMOJI_VOLUME_WATCH = '📡';
const EMOJI_DIAGNOSTIC_SYMBOL = '🔬';
const EMOJI_VOLUME_MA20 = '📈';
const EMOJI_VOLUME_BREAKOUT = '🔥';
const EMOJI_CANDLE = '🕯️';
const EMOJI_MANUAL = '🖐';

export {
  EMOJI_VIRTUAL,
  EMOJI_ORDER,
  EMOJI_WARNING,
  EMOJI_CHECK,
  EMOJI_CROSS,
  EMOJI_CLOSE,
  EMOJI_MOVE_DOWN,
  EMOJI_MOVE_UP,
  EMOJI_BALANCE,
  EMOJI_SETTINGS,
  EMOJI_TRIGGERS,
  EMOJI_LIST,
  EMOJI_DIAGNOSTIC,
  EMOJI_WEBSOCKET,
  EMOJI_CHART,
  EMOJI_WRENCH,
  EMOJI_PENDING,
  EMOJI_LONG,
  EMOJI_SHORT,
  EMOJI_NEAR_MISS,
  EMOJI_PAUSE,
  EMOJI_PLAY,
  EMOJI_INFO,
  EMOJI_STALE,
  EMOJI_LONG_DOT,
  EMOJI_SHORT_DOT,
  EMOJI_RESTART,
  EMOJI_UPTIME,
  EMOJI_CIRCUIT_BREAKER,
  EMOJI_TRADING_PAUSED,
  EMOJI_SOS,
  EMOJI_RULER,
  EMOJI_MULTI,
  EMOJI_SNAIL,
  EMOJI_MA_APPROACH,
  EMOJI_MA_CROSS,
  EMOJI_SCISSORS,
  EMOJI_VOLCANO,
  EMOJI_TARGET,
  EMOJI_SIGMA,
  EMOJI_PROFIT,
  EMOJI_SEARCH,
  EMOJI_ROBOT,
  EMOJI_DOOR,
  EMOJI_SCALE,
  EMOJI_NO_MA_TOUCH,
  EMOJI_VOLUME_WATCH,
  EMOJI_DIAGNOSTIC_SYMBOL,
  EMOJI_VOLUME_MA20,
  EMOJI_VOLUME_BREAKOUT,
  EMOJI_CANDLE,
  EMOJI_MANUAL,
};
